version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8.1.4
     steps:
       - checkout
       - run: echo "hello world"
   test:
     docker:
       - image: circleci/node:8.1.4
     steps:
       - checkout
       - run: echo "hello flow"


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test