version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8.1.4
     steps:
       - checkout
       - run:
          name: hello
          command: echo "hello world"
       - run:
          name: npm-install
          command: npm install
       - run:
          name: test
          command: npm run test

  security:
    machine: true
    steps:
      - checkout
      - run:
          name: security-checks
          command: bash ci/security-checks.sh

   deploy-stg:
     docker:
       - image: circleci/node:8.1.4
     steps:
       - checkout
       - run: echo "hello staging"

workflows:
  version: 2
  build_and_staging:
    jobs:
      - build
      - security
      - approve-stg:
          type: approval
          requires:
            - build
      - deploy-stg:
          requires:
            - approve-stg